= Learning transliteration from graphs

Mahdi Mohajeri and Jair Wuilloud
v1.0, 2022-04-0
:doctype: book
:docinfo:

== Introduction

=== General

===== Transliteration for Farsi


Transliteration is the process of transforming a language into another script, transforming the letters such as to maintain the sounds.
Languages are obviously subject to very complex rules making the above process quite complicated.
It is especially the case if no corpora are available to train neural networks or other techniques on.
No corpora are available with Farsi at the time of the creation of this library, and so we needed to build the transliteration strategy from scratch.

===== Innovative Approach

We present a novel approach to transliteration.
Our solution is data based in original ways:
Not only is transliteration learnt from multiple transliterations examples
but also the code is learnt/built from diagrams (graphs) that language experts
can design on their favourite chart technology.

Transliteration is approached this way because of
 the following problems:

 * Transliteration code based on highly complex sets of rules as
 in the https://github.com/interscript/transliteration-learner-from-graphs/blob/main/learn-graph/rules/rules.md[farsi case].
 * Language expert and developer's workflow are difficult to integrate as the developer
 is asked to encode complex rules he/she is likely to have little chances to comprehend.
 * As a result, not only the code takes a considerable amount of time to be written,
  it has little flexibility for tweaks or redesigns.

For these reasons, we are proposing an alternative approach consisting in:

  * Empowering language experts in the process or designing complex rules and logics
  * As a result, encapsulate and integrate both language expert and developer workflows
  * Build a flexible and solution that can be visualised and changed with
   with limited amount of work for developers

=== Building code from graphs

===== Learning
"Learning" logical graphs from data.

===== Assets

Mappings

===== Code structure to handle flows and recursions

* data flowing through logic
* jumps between node and their trigger
* Classes

===== Lucidchart as Editor and format

https://github.com/interscript/transliteration-learner-from-graphs/blob/main/learn-graph/resources/Model1.0.png[model 1.0]
and its https://github.com/interscript/transliteration-learner-from-graphs/blob/main/learn-graph/resources/Model1.0.csv[csv export].


=== Learning to transliterate with transformers

===== Transformers
blabla



=== Porting python transformers to ruby

===== OnnxRuntime
===== Implementation of greedy decoding



=== Discussion

===== Feedback from developers

===== Feedback from Language specialist



== Summary
