name: build

on:
  push:
  pull_request:
  repository_dispatch:
    types: [ 'interscript/interscript' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: |
          yarn install
          yarn global add asciidoctor
      - name: Build site
        run: |
          yarn adoc make

